import 'dart:convert';
import 'dart:io';

import 'package:resend_dart/resend_dart.dart';

import '../constants.dart';
import '../logging/logger_service.dart';

/// Result of a log share operation
class LogShareResult {
  final bool success;
  final String? dpasteUrl; // Deprecated, kept for compatibility if needed, but always null now
  final String? errorMessage;

  const LogShareResult({required this.success, this.dpasteUrl, this.errorMessage});
}

/// Service for sending email notifications with logs attached
class LogShareService {
  LogShareService._();
  static final LogShareService instance = LogShareService._();

  final _logger = LoggerService.instance;

  /// Sends an email notification with the logs attached via Resend API
  Future<bool> sendEmailNotification({
    required String logContent,
    String? userDescription,
    String? appVersion,
  }) async {
    _logger.info('Sending email with logs attached via Resend...', tag: 'LogShareService');

    try {
      final resend = Resend(apiKey: AppConstants.resendApiKey);

      final timestamp = DateTime.now().toIso8601String();
      final platform = Platform.operatingSystem;
      final platformVersion = Platform.operatingSystemVersion;

      final emailBody = StringBuffer()
        ..writeln('🎮 Game Size Manager - Bug Report')
        ..writeln('═══════════════════════════════════════════')
        ..writeln()
        ..writeln('📋 Details:')
        ..writeln('  • App Version: ${appVersion ?? AppConstants.appVersion}')
        ..writeln('  • Platform: $platform ($platformVersion)')
        ..writeln('  • Timestamp: $timestamp')
        ..writeln()
        ..writeln('📝 User Description:')
        ..writeln(userDescription?.isNotEmpty == true ? userDescription : 'No description provided')
        ..writeln()
        ..writeln('📎 Logs are attached to this email.')
        ..writeln()
        ..writeln('═══════════════════════════════════════════')
        ..writeln('This email was auto-generated by the Game Size Manager app.');

      // Create attachment
      // Using UTF-8 encoding for the log content
      final List<int> logBytes = utf8.encode(logContent);

      final attachment = ResendAttachment(
        filename: 'game_size_manager_logs.txt',
        content: logBytes,
      );

      await resend.email.send(
        from: 'GameSizeManager <onboarding@resend.dev>',
        to: [AppConstants.developerEmail],
        subject: '🎮 Bug Report - Game Size Manager (v${appVersion ?? AppConstants.appVersion})',
        text: emailBody.toString(),
        attachments: [attachment],
      );

      _logger.info('Email sent successfully', tag: 'LogShareService');
      return true;
    } catch (e, stackTrace) {
      _logger.error(
        'Failed to send email',
        error: e,
        stackTrace: stackTrace,
        tag: 'LogShareService',
      );
      return false;
    }
  }

  /// Complete flow: get logs and send email with attachment
  Future<LogShareResult> shareLogsWithDeveloper({String? userDescription}) async {
    _logger.info('Starting log sharing flow...', tag: 'LogShareService');

    try {
      // 1. Get log content
      final logContent = await _logger.getLogContent();
      if (logContent == null || logContent.isEmpty) {
        _logger.warning('No logs to share', tag: 'LogShareService');
        return const LogShareResult(
          success: false,
          errorMessage: 'No logs available to share. The log file may be empty.',
        );
      }

      // 2. Send email with attachment
      final emailSent = await sendEmailNotification(
        logContent: logContent,
        userDescription: userDescription,
      );

      if (!emailSent) {
        return const LogShareResult(
          success: false,
          errorMessage: 'Failed to send email. Please check your internet connection.',
        );
      }

      _logger.info('Log sharing completed successfully', tag: 'LogShareService');
      return const LogShareResult(success: true, dpasteUrl: null);
    } catch (e, stackTrace) {
      _logger.error(
        'Unexpected error during log sharing',
        error: e,
        stackTrace: stackTrace,
        tag: 'LogShareService',
      );
      return LogShareResult(
        success: false,
        errorMessage: 'An unexpected error occurred: ${e.toString()}',
      );
    }
  }
}
